{% set name = "caddy" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/caddyserver/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 955c840f3e5981d9b30e48f818d1f42f5f4765a13b3ec658e210d268b93a7cde
    folder: src
  - url: https://github.com/caddyserver/xcaddy/archive/refs/tags/v0.3.4.tar.gz
    sha256: 5ff7b73c2601ceaf3fd1b3d92be49244523b9b98ee6127276d54c4df59a73d28
    folder: xcaddy

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - caddy version
    - caddy --help

about:
  home: https://caddyserver.com
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
  dev_url: https://github.com/caddyserver/{{ name }}

extra:
  recipe-maintainers:
    - pavelzw
