{% set name = "caddy" %}
{% set version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/caddyserver/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ff73a9bd9968d63cae3d9f804d83e67759836a5331c9b13d04b30ebe86369722
    folder: src
  - url: https://github.com/caddyserver/xcaddy/archive/refs/tags/v0.3.4.tar.gz
    sha256: 5ff7b73c2601ceaf3fd1b3d92be49244523b9b98ee6127276d54c4df59a73d28
    folder: xcaddy

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - cd ../xcaddy
    - go run cmd/xcaddy/main.go build v$PKG_VERSION --output "$PREFIX/bin/caddy"  # [not win]
    - go run .\cmd\xcaddy\main.go build v%PKG_VERSION% --output "%LIBRARY_BIN%\caddy.exe"  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - caddy version
    - caddy --help

about:
  home: https://caddyserver.com
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
  dev_url: https://github.com/caddyserver/{{ name }}

extra:
  recipe-maintainers:
    - pavelzw
