{% set name = "caddy" %}
{% set version = "2.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/caddyserver/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 97f687c1d9fbe275952cc932639e8f0ab90cb7177961b02078fba989b4e29c31
    folder: src
  - url: https://github.com/caddyserver/xcaddy/archive/refs/tags/v0.3.4.tar.gz
    sha256: 5ff7b73c2601ceaf3fd1b3d92be49244523b9b98ee6127276d54c4df59a73d28
    folder: xcaddy

build:
  number: 1

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - caddy version
    - caddy --help

about:
  home: https://caddyserver.com
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
  dev_url: https://github.com/caddyserver/{{ name }}

extra:
  recipe-maintainers:
    - pavelzw
